services:
  - type: web
    name: drossiapi-web
    env: node
    plan: free
    buildCommand: "npm ci"
    startCommand: "node index.js"
    autoDeploy: true
    healthCheckPath: "/health"
    envVars:
      - key: NODE_ENV
        value: production
  - type: worker
    name: drossiapi-worker
    env: node
    plan: free
    buildCommand: "npm ci"
    startCommand: "node worker.js"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
